version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - 10000:10000